services:
  - type: web
    name: myportfolio-frontend
    runtime: static
    buildCommand: echo "Static site, no build needed"
    staticPublishPath: ./
    envVars:
      - key: NODE_VERSION
        value: 16.15.0
    routes:
      - type: rewrite
        source: /*
        destination: /index.html
